create view global_statistics_all_years as SELECT 
    acm.COUNTRY_ID, 
    acm.COUNTRY, 
    acm.GOVERNANCE, 
    acm.MARKETACCESSINFRASTRUCTURE, 
    acm.ECONOMICQUALITY, 
    acm.HEALTH, 
    acm.EDUCATION, 
    acm.LIFE_EXPECTANCY, 
    acm.PREVALENCE_OF_UNDERNOURISHMENT, 
    acm.HEALTH_EXPENDITURE_PERCENTAGE, 
    acm.EDUCATION_EXPENDITURE_PERCENTAGE, 
    acm.UNEMPLOYMENT, 
    acm.CORRUPTION, 
    acm.SOCIALCAPITAL, 
    
    acs.REPORT_YEAR, 
    acs.TOTAL_NEW_CASES, 
    acs.TOTAL_NEW_DEATHS, 
    
    adp.AVG_TEMPERATURE, 
    adp.AVG_BEDS_PER_1000, 
    adp.AVG_DOCTORS_PER_1000, 
    adp.AVG_GDP, 
    adp.AVG_POPULATION, 
    adp.AVG_MEDIAN_AGE, 
    adp.AVG_POPULATION_ABOVE_65, 
    adp.AVG_DAILY_TESTS, 
    adp.AVG_CASES, 
    adp.AVG_DEATHS, 
    
    amc.SCHIZOPHRENIA_PERCENTAGE, 
    amc.BIPOLAR_DISORDER_PERCENTAGE, 
    amc.EATING_DISORDERS_PERCENTAGE, 
    amc.ANXIETY_DISORDERS_PERCENTAGE, 
    amc.DRUG_USE_DISORDERS_PERCENTAGE, 
    amc.DEPRESSION_PERCENTAGE, 
    amc.ALCOHOL_USE_DISORDERS_PERCENTAGE 

FROM ALL_COUNTRIES_METRICS acm
LEFT JOIN ALL_COVID_STATISTICS acs 
    ON acm.COUNTRY_ID = acs.COUNTRY_ID
LEFT JOIN ALL_DOCTOR_PATIENTS adp 
    ON acm.COUNTRY_ID = adp.COUNTRY_ID 
LEFT JOIN ALL_MENTAL_COUNTRIES amc 
    ON acm.COUNTRY_ID = amc.id_row; 


select * from global_statistics_all_years where report_year=2023;

