--mental health data
SELECT MAX(YEAR) as maximum_year, MIN(YEAR) as minimum_year
FROM a1phra.mentalhealthdisorders;
---The years span from 1800 to 2019
CREATE TABLE a1phra.mental_before_1900 AS SELECT * FROM a1phra.mentalhealthdisorders WHERE 1=0;
CREATE TABLE a1phra.mental_before_2000 AS SELECT * FROM a1phra.mentalhealthdisorders WHERE 1=0;
CREATE TABLE a1phra.mental_before_2010 AS SELECT * FROM a1phra.mentalhealthdisorders WHERE 1=0;
CREATE TABLE a1phra.mental_after_2010 AS SELECT * FROM a1phra.mentalhealthdisorders WHERE 1=0;
---trigger to insert to each table
CREATE OR REPLACE TRIGGER trg_partition_by_year
BEFORE INSERT ON a1phra.mentalhealthdisorders
FOR EACH ROW
BEGIN
    IF :NEW.YEAR BETWEEN 1800 AND 1900 THEN
        INSERT INTO a1phra.mental_before_1900 
        (COUNTRY, CODE, YEAR, SCHIZOPHRENIA_PERCENTAGE, BIPOLAR_DISORDER_PERCENTAGE, 
        EATING_DISORDERS_PERCENTAGE, ANXIETY_DISORDERS_PERCENTAGE, 
        DRUG_USE_DISORDERS_PERCENTAGE, DEPRESSION_PERCENTAGE, ALCOHOL_USE_DISORDERS_PERCENTAGE)
        VALUES (:NEW.COUNTRY, :NEW.CODE, :NEW.YEAR, :NEW.SCHIZOPHRENIA_PERCENTAGE, 
        :NEW.BIPOLAR_DISORDER_PERCENTAGE, :NEW.EATING_DISORDERS_PERCENTAGE, 
        :NEW.ANXIETY_DISORDERS_PERCENTAGE, :NEW.DRUG_USE_DISORDERS_PERCENTAGE, 
        :NEW.DEPRESSION_PERCENTAGE, :NEW.ALCOHOL_USE_DISORDERS_PERCENTAGE);
        
    ELSIF :NEW.YEAR BETWEEN 1901 AND 2000 THEN
        INSERT INTO a1phra.mental_before_2000 
        VALUES (:NEW.COUNTRY, :NEW.CODE, :NEW.YEAR, :NEW.SCHIZOPHRENIA_PERCENTAGE, 
        :NEW.BIPOLAR_DISORDER_PERCENTAGE, :NEW.EATING_DISORDERS_PERCENTAGE, 
        :NEW.ANXIETY_DISORDERS_PERCENTAGE, :NEW.DRUG_USE_DISORDERS_PERCENTAGE, 
        :NEW.DEPRESSION_PERCENTAGE, :NEW.ALCOHOL_USE_DISORDERS_PERCENTAGE);
        
    ELSIF :NEW.YEAR BETWEEN 2001 AND 2010 THEN
        INSERT INTO a1phra.mental_before_2010 
        VALUES (:NEW.COUNTRY, :NEW.CODE, :NEW.YEAR, :NEW.SCHIZOPHRENIA_PERCENTAGE, 
        :NEW.BIPOLAR_DISORDER_PERCENTAGE, :NEW.EATING_DISORDERS_PERCENTAGE, 
        :NEW.ANXIETY_DISORDERS_PERCENTAGE, :NEW.DRUG_USE_DISORDERS_PERCENTAGE, 
        :NEW.DEPRESSION_PERCENTAGE, :NEW.ALCOHOL_USE_DISORDERS_PERCENTAGE);
        
    ELSIF :NEW.YEAR BETWEEN 2011 AND 2020 THEN
        INSERT INTO a1phra.mental_after_2010 
        VALUES (:NEW.COUNTRY, :NEW.CODE, :NEW.YEAR, :NEW.SCHIZOPHRENIA_PERCENTAGE, 
        :NEW.BIPOLAR_DISORDER_PERCENTAGE, :NEW.EATING_DISORDERS_PERCENTAGE, 
        :NEW.ANXIETY_DISORDERS_PERCENTAGE, :NEW.DRUG_USE_DISORDERS_PERCENTAGE, 
        :NEW.DEPRESSION_PERCENTAGE, :NEW.ALCOHOL_USE_DISORDERS_PERCENTAGE);
    END IF;
END;
/
--Using only 2010 and above data
select * from a1phra.mental_after_2010;
--updating the table
UPDATE a1phra.mental_after_2010
SET 
    SCHIZOPHRENIA_PERCENTAGE = CASE WHEN SCHIZOPHRENIA_PERCENTAGE > 100 OR SCHIZOPHRENIA_PERCENTAGE IS NULL THEN 1.0 ELSE SCHIZOPHRENIA_PERCENTAGE END,
    BIPOLAR_DISORDER_PERCENTAGE = CASE WHEN BIPOLAR_DISORDER_PERCENTAGE > 100 OR BIPOLAR_DISORDER_PERCENTAGE IS NULL THEN 1.0 ELSE BIPOLAR_DISORDER_PERCENTAGE END,
    EATING_DISORDERS_PERCENTAGE = CASE WHEN EATING_DISORDERS_PERCENTAGE > 100 OR EATING_DISORDERS_PERCENTAGE IS NULL THEN 1.0 ELSE EATING_DISORDERS_PERCENTAGE END,
    ANXIETY_DISORDERS_PERCENTAGE = CASE WHEN ANXIETY_DISORDERS_PERCENTAGE > 100 
    OR ANXIETY_DISORDERS_PERCENTAGE IS NULL THEN 1.0 ELSE ANXIETY_DISORDERS_PERCENTAGE END,
    DRUG_USE_DISORDERS_PERCENTAGE = CASE WHEN DRUG_USE_DISORDERS_PERCENTAGE > 100 
    OR DRUG_USE_DISORDERS_PERCENTAGE IS NULL THEN 1.0 ELSE DRUG_USE_DISORDERS_PERCENTAGE END,
    DEPRESSION_PERCENTAGE = CASE WHEN DEPRESSION_PERCENTAGE > 100 OR DEPRESSION_PERCENTAGE IS NULL THEN 1.0 ELSE DEPRESSION_PERCENTAGE END,
    ALCOHOL_USE_DISORDERS_PERCENTAGE = CASE WHEN ALCOHOL_USE_DISORDERS_PERCENTAGE > 100 
    OR ALCOHOL_USE_DISORDERS_PERCENTAGE IS NULL THEN 1.0 ELSE ALCOHOL_USE_DISORDERS_PERCENTAGE END;

--Selecting only countries from the countries table

create view all_mental_countries as SELECT a1.country, c.id_row,
ROUND(avg(a1.SCHIZOPHRENIA_PERCENTAGE),2) AS SCHIZOPHRENIA_PERCENTAGE,
ROUND(avg(a1.BIPOLAR_DISORDER_PERCENTAGE),2) AS BIPOLAR_DISORDER_PERCENTAGE,
ROUND(avg(a1.EATING_DISORDERS_PERCENTAGE),2) AS EATING_DISORDERS_PERCENTAGE,
ROUND(avg(a1.ANXIETY_DISORDERS_PERCENTAGE),2) AS ANXIETY_DISORDERS_PERCENTAGE,
ROUND(avg(a1.DRUG_USE_DISORDERS_PERCENTAGE),2) AS DRUG_USE_DISORDERS_PERCENTAGE,
ROUND(avg(a1.DEPRESSION_PERCENTAGE),2) AS DEPRESSION_PERCENTAGE,
ROUND(avg(a1.ALCOHOL_USE_DISORDERS_PERCENTAGE),2) AS ALCOHOL_USE_DISORDERS_PERCENTAGE
FROM a1phra.mental_after_2010 a1
JOIN a1phra.countries c ON a1.country = c.name group by a1.country,c.id_row order by c.id_row;


