---partitioning into each year 
--creating anew table with partioned data


CREATE TABLE A1PHRA.COUNTRY_YEAR_INDICATORS_PART (
    COUNTRY VARCHAR2(100) NOT NULL,
    COUNTRY_CODE VARCHAR2(10),
    REGION VARCHAR2(50),
    INCOMEGROUP VARCHAR2(50),
    YEAR NUMBER(38,0) ,
    LIFE_EXPECTANCY_WORLD_BANK FLOAT,
    PREVALENCE_OF_UNDERNOURISHMENT FLOAT,
    CO2 FLOAT,
    HEALTH_EXPENDITURE_PERCENTAGE FLOAT,
    EDUCATION_EXPENDITURE_PERCENTAGE FLOAT,
    UNEMPLOYMENT FLOAT,
    CORRUPTION FLOAT,
    SANITATION FLOAT,
    INJURIES FLOAT,
    COMMUNICABLE FLOAT,
    NONCOMMUNICABLE FLOAT,
    CONSTRAINT PK_COUNTRY_YEAR_PART PRIMARY KEY (COUNTRY,YEAR)
)
PARTITION BY RANGE (YEAR) ( 
    PARTITION p_before_2000 VALUES LESS THAN (2000),
    PARTITION p_2000_2009 VALUES LESS THAN (2010),
    PARTITION p_2010_2019 VALUES LESS THAN (2020),
    PARTITION p_2020_2029 VALUES LESS THAN (2030),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);


---inserting data
INSERT INTO A1PHRA.COUNTRY_YEAR_INDICATORS_PART


SELECT * FROM A1PHRA.COUNTRY_YEAR_INDICATORS 

