---primary keys
ALTER TABLE A1PHRA.COUNTRY_YEAR_INDICATORS ADD CONSTRAINT PK_COUNTRY_YEAR_INDICATOR PRIMARY KEY (COUNTRY,YEAR);
ALTER TABLE A1PHRA.DOCTOR_PATIENT ADD CONSTRAINT PK_DOCTORPATIENT PRIMARY KEY (COUNTRY,DATES);
ALTER TABLE A1PHRA.COUNTRYSCORES ADD CONSTRAINT PK_COUNTRYSCORES PRIMARY KEY (COUNTRY);




