CREATE TABLE Diabetes (
    HEARTDISEASEORATTACK NUMBER(1,0),
    HIGHBP NUMBER(1,0),
    HIGHCHOL NUMBER(1,0),
    CHOLCHECK NUMBER(1,0),
    BMI NUMBER(5,2),
    SMOKER NUMBER(1,0),
    STROKE NUMBER(1,0),
    DIABETES NUMBER(1,0),
    PHYSACTIVITY NUMBER(1,0),
    FRUITS NUMBER(1,0),
    VEGGIES NUMBER(1,0),
    HVYALCOHOLCONSUMP NUMBER(1,0),
    ANYHEALTHCARE NUMBER(1,0),
    NODOCBCCOST NUMBER(1,0),
    GENHLTH NUMBER(1,0),
    MENTHLTH NUMBER(3,0),
    PHYSHLTH NUMBER(3,0),
    DIFFWALK NUMBER(1,0),
    SEX VARCHAR2(10 BYTE),
    AGE NUMBER(3,0),
    EDUCATION VARCHAR2(50 BYTE),
    INCOME VARCHAR2(50 BYTE)
);

CREATE TABLE COUNTRY_YEAR_INDICATORS (
    COUNTRY VARCHAR2(100 BYTE),
    COUNTRY_CODE VARCHAR2(10 BYTE),
    REGION VARCHAR2(50 BYTE),
    INCOMEGROUP VARCHAR2(50 BYTE),
    YEAR NUMBER(38,0),
    LIFE_EXPECTANCY_WORLD_BANK FLOAT,
    PREVALENCE_OF_UNDERNOURISHMENT FLOAT,
    CO2 FLOAT,
    HEALTH_EXPENDITURE_PERCENTAGE FLOAT,
    EDUCATION_EXPENDITURE_PERCENTAGE FLOAT,
    UNEMPLOYMENT FLOAT,
    CORRUPTION FLOAT,
    SANITATION FLOAT,
    INJURIES FLOAT,
    COMMUNICABLE FLOAT,
    NONCOMMUNICABLE FLOAT
);

CREATE TABLE DOCTOR_PATIENT (
    COUNTRY VARCHAR2(255 BYTE),
    CONTINENT VARCHAR2(255 BYTE),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    AVERAGETEMPERATURE FLOAT,
    BEDSPER1000 FLOAT,
    DOCTORSPER1000 FLOAT,
    GDP FLOAT,
    POPULATION NUMBER,
    MEDIANAGE NUMBER,
    POPULATIONABOVE65 FLOAT,
    DATES VARCHAR2(255 BYTE),
    DAILYTESTS NUMBER,
    CASES NUMBER,
    DEATHS NUMBER,
    REPORT_MONTH NUMBER,
    REPORT_YEAR NUMBER
);
CREATE TABLE GLOBAL_COVID_STATISTICS (
    DATE_REPORTED DATE,
    COUNTRY_CODE VARCHAR2(10 BYTE),
    COUNTRY VARCHAR2(100 BYTE),
    CONTINENT VARCHAR2(50 BYTE),
    WHO_REGION VARCHAR2(50 BYTE),
    NEW_CASES NUMBER(38,0),
    CUMULATIVE_CASES NUMBER(38,0),
    NEW_DEATHS NUMBER(38,0),
    CUMULATIVE_DEATHS NUMBER(38,0),
    REPORT_MONTH NUMBER,
    REPORT_YEAR NUMBER,
    CASES_BEFORE NUMBER
);

CREATE TABLE MENTALHEALTHDISORDERS (
    COUNTRY VARCHAR2(255 BYTE),
    CODE VARCHAR2(10 BYTE),
    YEAR NUMBER,
    SCHIZOPHRENIA_PERCENTAGE FLOAT,
    BIPOLAR_DISORDER_PERCENTAGE FLOAT,
    EATING_DISORDERS_PERCENTAGE FLOAT,
    ANXIETY_DISORDERS_PERCENTAGE FLOAT,
    DRUG_USE_DISORDERS_PERCENTAGE FLOAT,
    DEPRESSION_PERCENTAGE FLOAT,
    ALCOHOL_USE_DISORDERS_PERCENTAGE FLOAT
);

